# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConsultapedidos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_consultapedidos(self):
    self.driver.get("https://totvs.grendene.com.br/josso/signon/login.do")
    self.driver.set_window_size(1280, 773)
    self.driver.find_element(By.ID, "txtPassword").send_keys("SENHA_TOTVS")
    self.driver.find_element(By.ID, "chkDomain").click()
    self.driver.find_element(By.ID, "txtDomain").send_keys("gra_sid")
    self.driver.find_element(By.ID, "btn-enter").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".ng-binding:nth-child(3) > .hidden-xs")))
    self.driver.find_element(By.CSS_SELECTOR, ".ng-binding:nth-child(3) > .hidden-xs").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".ng-scope:nth-child(18) > .col-lg-5")))
    element = self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(18) > .col-lg-5")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(18) > .col-lg-5")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(18) > .col-lg-5")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-scope:nth-child(18) > .col-lg-5").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".btn-primary")))
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.vars["win3557"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3557"])
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.NAME, "w_cod_cliente").click()
    self.driver.find_element(By.NAME, "w_cod_cliente").send_keys("50000")
    self.driver.find_element(By.NAME, "w_cod_cliente").send_keys(Keys.ENTER)
    self.driver.find_element(By.NAME, "w_cod_rep").click()
    self.driver.find_element(By.NAME, "w_nome_abrev").click()
    self.driver.find_element(By.NAME, "w_cod_rep").click()
    self.driver.find_element(By.NAME, "w_cod_rep").click()
    self.driver.find_element(By.NAME, "w_cod_rep").click()
    element = self.driver.find_element(By.NAME, "w_cod_rep")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) tr:nth-child(1)").click()
    self.driver.find_element(By.NAME, "w_cod_cliente").send_keys("rgsrrrherh")
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
  
