# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPedidosclientescentralizador():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pedidosclientescentralizador(self):
    self.driver.get("https://totvs-webspeed.grendene.com.br/cgi-bin/wspd_cgi116.sh/WService=totvswebext/web/men/wrun.w")
    self.driver.set_window_size(1280, 773)
    self.driver.switch_to.frame(1)
    WebDriverWait(self.driver, 30).until(expected_conditions.element_to_be_clickable((By.NAME, "w_cod_cliente")))
    self.driver.find_element(By.NAME, "w_cod_cliente").send_keys("1031462")
    self.driver.find_element(By.NAME, "w_cod_rep").send_keys("74800")
    self.driver.find_element(By.NAME, "w_dt_implantacao_ini").send_keys("16022000")
    self.driver.find_element(By.NAME, "w_prev_emb").send_keys("03032021")
    self.driver.find_element(By.NAME, "w_status").click()
    dropdown = self.driver.find_element(By.NAME, "w_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Todos']").click()
    self.driver.find_element(By.NAME, "I11").click()
  
